### ISSUE TITLE
"use strict";

### ISSUE THREAD

**Issue by RichardLitt** [yyx990803/semi#2]
If you're using `"use strict";`, according to JSHint you should have the ; after it. Could we not remove it, for this case only?

**Comment by yyx990803** [comment]
It is valid without the semicolon, and will correctly activate strict mode, so I don't really see the point of adding semicolon for this case only (or why JSHint thinks so).

**Comment by RichardLitt** [comment]
It is valid. The issues are further delineated here https://github.com/jshint/jshint/issues/459 and here https://github.com/twbs/bootstrap/issues/1905. 

The main reason to make this exception is that JSHint doesn't provide an option to turn off checking for ; after 'use strict', which means that I am bound to get an error if semi removes it.

**Comment by hax** [comment]
@RichardLitt That's the bug of jshint, which they should fix it.

**Comment by RichardLitt** [comment]
Just checked again; sorry, it isn't technically valid. The Spec mandates the use of the semicolon here, for 'use strict'. While it will activate strict mode, it is invalid according to the spec. 

> A Directive Prologue is the longest sequence of ExpressionStatement productions occurring as the initial SourceElement productions of a Program or FunctionBody and where each ExpressionStatement in the sequence consists entirely of a StringLiteral token followed a semicolon. The semicolon may appear explicitly or may be inserted by automatic semicolon insertion. A Directive Prologue may be an empty sequence.

[Source](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf)
This isn't a jshint bug. It's a bug with semi not conforming to spec.

**Comment by yyx990803** [comment]
"The semicolon may appear explicitly or may be inserted by automatic semicolon insertion"?

**Comment by RichardLitt** [comment]
Would it automatically get inserted by the parser?

**Comment by yyx990803** [comment]
That's what ASI means.

**Comment by RichardLitt** [comment]
Ah. Ok, cheers.
