### ISSUE TITLE
sublime插件

### ISSUE THREAD

**Issue by jieyou** [yyx990803/semi#9]
感谢制作出了这样实用的命令行工具。

考虑基于此推出sublime的添加/移除分号的插件？

目前开发中对于此类对js文件格式上的修改，我觉得考虑推出一个sublime插件可能会有更多用户，常用的同类工具比如jsFormat就有sublime和其他ide的插件，并且获得了广泛的使用

**Comment by yyx990803** [comment]
Readme 里就提到了：https://github.com/yyx990803/semi-sublime
